[allowlist]
description = "Allowlist for non-sensitive example files"
paths = [
  '''^\.env\.example$''',
  '''^docs/.*$'''
]

[rules]
# Varsayılan kuralları kullan (yeni sızıntıları yakala). Burada özel rule tanımlamıyoruz.

