version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: orcaquant_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/orcaquant_test
      REDIS_URL: redis://redis:6379/0
      FLASK_ENV: production
      ORCAQUANT_SEED: "1"
      FLASK_APP: backend.app:create_app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      sh -c "
      flask db upgrade || true &&
      python -m backend.seeds.seed_basic &&
      gunicorn 'backend.app:create_app()' -b 0.0.0.0:8000 --workers 2 --threads 4 --timeout 90
      "

