name: ytd-kopya-staging
services:
  reverse-proxy:
    image: caddy:2.8
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - STAGING_FQDN=${STAGING_FQDN}
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      backend:
        condition: service_healthy

  backend:
    image: ${BACKEND_IMAGE}
    restart: unless-stopped
    env_file:
      - .env.staging
    environment:
      - APP_IMPORT_CANDIDATES=${APP_IMPORT_CANDIDATES:-backend.app:create_app,backend.app:app,app:create_app,app:app}
      - GUNICORN_WORKERS=4
      - GUNICORN_THREADS=4
      - PORT=8000
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys;u=urllib.request.urlopen(\'http://127.0.0.1:8000/healthz\',timeout=3); sys.exit(0 if u.getcode()==200 else 1)\""]
      interval: 15s
      timeout: 5s
      retries: 10
    networks:
      - web

  frontend:
    profiles:
      - ui
    image: ${FRONTEND_IMAGE}
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
