apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: ytd
  labels:
    app: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: beat
          image: your-registry/ytd-backend:latest
          imagePullPolicy: IfNotPresent
          command: ["bash","-lc","celery -A backend.celery_app beat --loglevel=INFO"]
          envFrom:
            - configMapRef:
                name: backend-env
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
