apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: ytd
  labels:
    app: celery-worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: worker
          image: your-registry/ytd-backend:latest
          imagePullPolicy: IfNotPresent
          command: ["bash","-lc","celery -A backend.celery_app worker --loglevel=INFO --concurrency=4 --max-tasks-per-child=200 --max-memory-per-child=300000 --prefetch-multiplier=1"]
          envFrom:
            - configMapRef:
                name: backend-env
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
