name: Run Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu indir
        uses: actions/checkout@v3

      - name: Python ortamını hazırla
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Sanal ortamı oluştur ve aktif et
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          echo "=== Yüklenen paketler ==="
          pip list | grep -i flask
          echo "=== flask_socketio kontrolü ==="
          python -c "import flask_socketio; print('flask_socketio başarıyla import edildi')"

      - name: Pytest çalıştır (coverage ile)
        env:
          TESTING: 1
          FLASK_ENV: testing
        run: |
          source .venv/bin/activate
          pytest --cov=backend --cov-report=term-missing

