name: Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: pip install pip-audit cyclonedx-bom
      - name: Run pip-audit
        id: audit
        continue-on-error: true
        run: |
          for f in backend/requirements*.txt; do
            pip-audit -r "$f" -f json -o "pip-audit-$(basename "$f").json" --fail-on critical
          done
      - name: Generate SBOM
        run: |
          for f in backend/requirements*.txt; do
            cyclonedx-py -r "$f" --format json -o "sbom-$(basename "$f").json"
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            pip-audit-*.json
            sbom-*.json
          if-no-files-found: ignore
      - name: Fail on vulnerability
        if: steps.audit.outcome == 'failure'
        run: exit 1
